version: '3'

services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - default
    restart: always

  redis:
    image: redis:7.0.5
    container_name: redis
    command: redis-server --requirepass changeme --port 6379
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - '6379:6379'
    networks:
      - default

  # npm install && npm run start:dev;
  nodejs:
    image: pets
    build: .
    container_name: webserver
    working_dir: /usr/src/app
    command: >
      bash -c "
        while ! nc -z mariadb 3306;
        do
          sleep 5;
        done;
      "
    depends_on:
      - mariadb
      - redis
    ports:
      - '8080:8080'
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    networks:
      - default

networks:
  default:
